spring:
    mail:
      password: l1016482011
      username: 15151837009@163.com
      default-encoding: UTF-8
      port: 587
      properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      properties.mail.debug: true
      host: smtp.163.com

    h2:
      console:
        path: /h2-console
        enabled: true
    servlet:
      multipart:
        max-file-size: 1024KB
        max-request-size: 1024KB
    http:
      multipart:
        enabled: false
    thymeleaf:
      cache: false
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:hsqldb:file:~/.h2/resouce1
      username: sa
      password: sa
      driverClassName: org.hsqldb.jdbcDriver

debug: true
logging:
  level:
    org.springframework.security: INFO

images:
    path: images/files/
